config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'


  resources :simulations
  get "/discover", to: "pages#discover", as: "landing_page"

  get 'invoice_paid/:id', to: 'invoices#invoice_paid', as: 'invoice_paid'

  resources :invoices do
    member do
      post :send_to_client
    end

    resources :missions_invoices
  end

  resources :clients, only: [:show, :new, :create, :edit, :update]
  resources :missions, only: [:new, :create]
  resources :notifications, only: [:show, :index, :new, :create]

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount ActionCable.server => "/cable"
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :user
  belongs_to :client
  has_many :missions_invoices, dependent: :destroy
  has_many :missions, through: :missions_invoices
  accepts_nested_attributes_for :missions_invoices, reject_if: :all_blank, allow_destroy: true

  enum status: [:draft, :submitted, :sent, :paid, :delayed, :archived]

  before_save :generate_reference
  before_save :set_total_amounts
  before_save :set_due_date

  before_save :notif_delayed


  validates :title, presence: true
  validates :creation_date, presence: true
  validates :status, presence: true

  scope :to_be_delayed, -> { where('due_date < ?', Date.today).where.not(status: :paid) }

  def generate_reference
    self.reference = "#{self.user.first_name.split("").first}#{self.user.last_name.split("").first}-#{id}"
  end

  def set_total_amounts
    self.total_amount_ttc = missions_invoices.inject(0) { |s, m_i| s + (m_i.man_day_quantity * m_i.price_rate * (1 + m_i.vat_rate)) }
    self.total_amount_ht = missions_invoices.inject(0) { |s, m_i| s + (m_i.man_day_quantity * m_i.price_rate) }
  end

  def set_due_date
    self.due_date = creation_date + 30.days
  end

  def notif_delayed
    if self.status == "delayed"
      new_notif_delayed = Notification.create(user: self.user,
        category: "Paiement en retard",
        content: "Votre client #{self.client.company_name} ne vous a toujours pas réglé la facture #{self.reference} d'un montant de #{self.total_amount_ttc}€. Le paiement était dû au #{self.due_date}." )
    end
  end

  def get_due_date
    self.due_date.strftime("%d/%m/%Y")
  end

  def get_creation_date
    self.creation_date.strftime("%d/%m/%Y")
  end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

before_action :set_invoice, only: [:show, :edit, :update, :destroy, :send_to_client, :calcul_total_amount_ht]

# skip_before_action :authenticate_user!

  def index
    invoices = Invoice.where(user: current_user).order(created_at: :desc)
    if params[:query].present?
      sql_query = "invoices.title ILIKE :query OR clients.company_name ILIKE :query OR invoices.reference ILIKE :query"
      @invoices = invoices.joins(:client).where(sql_query, query: "%#{params[:query]}%")
    else
      @invoices = invoices.all
    end
  end

  def new
    @invoice = Invoice.new
    @invoice.missions_invoices.build
    @my_clients = current_user.clients


    if params[:search]
      @client_found = Client.find(params[:search][:client]) if Client.find(params[:search][:client]).present?
    end
  end
# I added in the show action of the invoices the method either to see the html version
# of the invoice, or the pdf one.

  def show
    respond_to do |format|
      format.html
      format.pdf do
        @format = 'pdf'

        render pdf: "Invoice No. #{@invoice.reference}",
          page_size: 'A4',
          template: "invoices/show.html.erb",
          layout: "pdf.html",
          orientation: "Portrait",
          lowquality: true,
          zoom: 1,
          dpi: 75,
          encoding: 'utf-8'
      end
    end
  end

  def create
    @invoice = Invoice.new(invoice_params)
    @invoice.user = current_user
    @invoice.client = Client.find(params[:client])
    @my_clients = current_user.clients
    if @invoice.save
      render :show
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @invoice.destroy
  end


  def invoice_paid
    @invoice = Invoice.find(params[:id])
    @invoice.paid!
    @invoice.update(payment_date: Date.today)
    new_notif_paid = Notification.create(user: current_user,
        category: "Paiement reçu !",
        content: "La facture numero #{@invoice.reference} vient d'être réglée par votre client #{@invoice.client.company_name}, pour un montant total de #{@invoice.total_amount_ttc} euros TTC." )
    respond_to do |format|
      format.js
      format.html { redirect_to root_path }
    end
  end

  def send_to_client
    @invoice.sent!
    @invoice.generate_reference
    new_notif_sent = Notification.create(user: current_user,
      category: "Facture envoyée",
      content: "Vous venez d'envoyer la facture #{@invoice.reference} à votre client #{@invoice.client.company_name}, pour un montant total de #{@invoice.total_amount_ttc}. Votre client a jusqu'au #{@invoice.due_date} pour la régler."
    )
    # InvoiceMailer.send_to_client(@invoice).deliver_now
    # InvoiceMailer.send_to_client(@invoice.id).deliver_now
    redirect_to root_path
    flash[:notice] = "Votre facture a bien été envoyée !"
  end

  private

  def set_invoice
    @invoice = Invoice.find(params[:id])
  end
  def invoice_params
    params.require(:invoice).permit(:client_id, :title, :creation_date, :due_date, missions_invoices_attributes: [:id, :mission_id, :man_day_quantity, :price_rate, :vat_rate, :amount, :_destroy])
  end
end

app/views/invoices/_invoice_form.html.erb
<%= simple_form_for :search, url: new_invoice_path, method: :get do |f| %>
        <div class="client p-2">
          <%= f.input :client, label:"Sélectionnez un client", collection: @my_clients, label_method: :company_name, value_method: :id, include_blank: true, as: :select %>
          <% if @client_found.present? %>
            <%= @client_found.company_name %> <br/>
            <%= @client_found.last_name %> <br/>
            <%= @client_found.company_address %>
          <% end %>
        </div>
      </div>
    <% end %>

    <%= simple_form_for @invoice do |f| %>
      <% if params[:search] %>
        <%= hidden_field_tag :client, @client_found.id %>
      <% end %>


      <%#= f.input :creation_date, as: :string, required: false, label: "Date de facturation",input_html: {class: "datepicker d-inline-flex p-3"} %>

      <div class="datepickere d-inline-flex p-2">
      <%= f.input :creation_date, label: "Date de facturation" %>
    </div>


    <div class="titre p-2">
      <%= f.input :title, label: "Titre" %>
    </div>
<% end %>

app/views/invoices/_missions_invoice_fields.html.erb
<div class= "nested-fields d-flex justify-content-between">

<!--   <div class="mission-name flex-grow-1"> -->
    <%= f.association :mission, label: "Intitulé de la mission", label_method: :name, value_method: :id, include_blank: true, input_html: {class: "mission-name flex-grow-1"} %>


<!--   </div> -->
  <!-- <div class="quantity"> -->

    <%=   f.input :man_day_quantity, label: "Qté (jours)", placeholder:"jours", as: :integer, input_html: {class: "w-input"} %>

<!--    </div> -->
<!--   <div class="unit-price">  -->
    <%=   f.input :price_rate, label: "Prix (€)", placeholder:"euros",as: :integer, input_html: {class: "x-input"}%>
<!--   </div>
  <div class="tva"> -->
    <%=   f.input :vat_rate, label: "TVA", collection: MissionsInvoice::VAT, include_blank: false, input_html: {class: "y-input"} %>

<!--  </div> -->
      <div class="montant d-flex flex-column">
        <p>Montant HT</p>
        <div class="total-line-HT"> &nbsp;</div>
      </div>

      <div class="montant d-flex flex-column">
        <p>Montant TTC</p>
        <div class="total-line-TTC"> &nbsp;</div>
      </div>

  <div class="remove-line">
    <%=   link_to_remove_association "<i class='fas fa-times-circle'></i>".html_safe, f %>
  </div>
</div>

app/views/invoices/destroy.js.erb
var invoice = document.getElementById("invoice-div-<%= @invoice.id %>")
invoice.remove()

app/views/invoices/edit.html.erb
<div class="container">

  <h2>Edit your invoice :</h2>

  <%= render 'invoice_form', invoice: @invoice %>

</div>

app/views/invoices/index.html.erb
<div class="container">

  <!-- <div class="invoices_index_title">
    <h1><i class="far fa-file-alt"></i>  Mes factures :</h1>
  </div> -->


  <div class="search-invoice">
  <%= form_tag invoices_path, method: :get, class: "form-inline" do %>
    <label for="inp" class="inp">
      <%= text_field_tag :query, params[:query], id: 'inp', placeholder: "  " %>
      <span class="label"><i class="fas fa-search"></i>Trouver une facture</span>
    </label>
  <%#= submit_tag "Rechercher", class: "button submit-index-search" %>
  <% end %>
</div>

  <!-- <div class="color-line"></div> -->

  <div class="invoices-array">

    <div class="array-header d-flex">

      <div class="array-header-column">
        <h4>Titre</h4>
      </div>
      <div class="array-header-column">
        <h4>Client</h4>
      </div>
      <div class="array-header-column">
        <h4>Date de création</h4>
      </div>
      <div class="array-header-column">
        <h4>Référence</h4>
      </div>
      <div class="array-header-column">
        <h4>Statut</h4>
      </div>
      <div class="array-header-column">
        <h4>Montant TTC</h4>
      </div>
      <div class="array-header-column invoice-actions">
      </div>

    </div>

    <% @invoices.each do |invoice| %>

    <div class="invoices-card d-flex" id="invoice-div-<%= invoice.id %>">

      <div class="invoice-infos infos-titre">
       <%= invoice.title %>
      </div>

      <div class="invoice-infos">
        <%= invoice.client.company_name  %>
      </div>

      <div class="invoice-infos">
        <%= invoice.get_creation_date %>
      </div>

      <div class="invoice-infos">
        <div class="statut">
          <%= invoice.reference %>
        </div>
      </div>

      <div class="invoice-infos infos-status">
        <p class="<%= invoice.status.to_s %> mb-0">
          <i class="fas fa-circle"></i> <%= invoice.status %>
        </p>
      </div>

      <div class="invoice-infos">
        <p class="mb-0">
          <%=  number_with_delimiter(invoice.total_amount_ht, delimiter: " ") %> €
        </p>
      </div>


      <div class="invoice-infos invoice-actions dropdown">

      <i class="fas fa-ellipsis-h" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
      <div class="dropdown-menu" aria-labelledby="dropdownMenu2">

      <!-- Show -->
      <%= link_to invoice_path(invoice.id), method: :get, class: 'dropdown-item' do %>
          <i class="fas fa-search-plus"></i>Aperçu
      <% end %>



      <!-- Send -->
      <%= link_to send_to_client_invoice_path(invoice.id), method: :post, class: 'dropdown-item' do %>
        <i class="far fa-paper-plane"></i>Envoyer
      <% end %>

        <!-- Edit -->
        <%# if invoice.status == "draft" %>
          <%#= link_to edit_invoice_path(invoice.id), class: 'dropdown-item' do %>
            <!-- <i class="fas fa-edit"></i>Editer -->
          <%# end %>
        <%# end %>



        <!-- Download -->
        <!-- <button class="dropdown-item" type="button"><i class="fas fa-download"></i>Télécharger</button> -->



        <!-- Print -->
        <!-- <button class="dropdown-item" type="button"><i class="fas fa-print"></i>Imprimer</button> -->



        <!-- Delete -->
        <% if invoice.status == "draft" %>
          <%= link_to invoice_path(invoice.id), method: :delete, remote: true, data: { confirm: "Êtes vous sûr de vouloir supprimer : #{invoice.title} - #{invoice.reference}?" }, class: 'dropdown-item' do %>
              <i class="far fa-trash-alt"></i>Supprimer
            <% end %>
          <% end %>

        </div>

      </div>

    </div>

    <% end %>

  </div>
  <div class="invoices-index-buttons">
    <%= link_to "Nouvelle facture", new_invoice_path, class: "button-big" %>
  </div>
</div>

app/views/invoices/invoice_paid.js.erb
console.log('Facture payée !')

app/views/invoices/new.html.erb
<!-- <div class= "container py-5" style="width: 80%"> -->

<div class="create-invoice-container">
  <h1 class="mb-4">Créer une facture</h1>

  <div class="header-facture d-flex justify-content-between">
    <div>
      <%= current_user.first_name %>
      <%= current_user.last_name %> <br/>
      <%= current_user.address %> <br/>
      <span> Numéro de Siret : <%= current_user.siret %> </span><br/>
    </div>


    <%= simple_form_for :search, url: new_invoice_path, method: :get do |f| %>
        <div class="client-select">
          <%= f.input :client, label:"Sélectionnez un client", collection: @my_clients, label_method: :company_name, value_method: :id, include_blank: true, as: :select %>
          <% if @client_found.present? %>
            <%= @client_found.company_name %> <br/>
            <%= @client_found.last_name %> <br/>
            <%= @client_found.company_address %> <br/>
          <% end %>
    <%#= link_to 'Ajouter un nouveau client', new_client_path, class:"button-big" %>

    <!-- Button trigger modal -->
        </div>
    <button type="button" class="button-big" data-toggle="modal" data-target=".bd-example-modal-lg">
      Ajouter un nouveau client
    </button>
      </div>
    <% end %>

    <%= simple_form_for @invoice do |f| %>
      <% if params[:search] %>
        <%= hidden_field_tag :client, @client_found.id %>
      <% end %>




      <%#= f.input :creation_date, as: :string, required: false, label: "Date de facturation",input_html: {class: "datepicker d-inline-flex p-3"} %>
    <div style="width: 30%">
      <%= f.input :creation_date, as: :string, required: false, input_html: {class: "datepicker"}, placeholder: "Date de facturation", label: false %>


      <%= f.input :title, placeholder: "Titre de la facture",label: false %>
    </div>



        <h3 class="mt-5">Missions</h3>

        <div id="missions_invoices">
            <%= f.fields_for :missions_invoices do |missions_invoice| %>
              <%= render 'missions_invoice_fields', f: missions_invoice %>
            <% end %>

            <div class="links d-flex justify-content-between">
              <%= link_to_add_association 'Ajouter une ligne', f, :missions_invoices, class:"button-big" %>
            </div>
            <div class="calc-total d-flex align-items-end flex-column mb-3">
              <div class="d-flex">
                <p style="padding-top: 8px">
                MONTANT TOTAL HT</p>
                <div class="total-HT"> &nbsp; </div>
              </div>
              <div class="d-flex">
                <p style="padding-top: 8px">MONTANT TOTAL TTC</p>
                <div class="total-TTC"> &nbsp;</div>
              </div>

              <!-- <div class=""> -->
                <%= f.submit "Valider", class:"bouton-valider-form-invoice" %>
             <!--  </div> -->
            </div>
        <% end %>
    </div>
  <!-- </div> -->
</div>





<!-- Modal -->
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Ajouter un nouveau client</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render '/clients/form', client: Client.new %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/invoices/show.html.erb
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
</head>

<body>
  <div class="container">

    <% unless @format == 'pdf' %>
      <div class="invoice-show-action-buttons">
        <%= link_to "PDF", invoice_path(@invoice, format: :pdf), target: "_blank", class: "button button_pdf" %>
      <%= link_to 'Envoyer', send_to_client_invoice_path(@invoice), method: :post, class: 'button button_envoi hidden-link' %>
      </div>
    <% end %>

    <div class="invoice-box">
      <table>
        <tr class="top">
          <td colspan="4">
            <table>
              <tr class="freelance-logo-and-invoice-summary">
                <td class="freelance-big-logo-on-pdf-invoice">
                  <div class="user-invoice-logo">
                    <%= image_tag image_url('user_logo3.png') %>
                    <%#= wicked_pdf_image_tag 'user_logo3.png' %>
                  </div>

                </td>

                <td class="infos-factures-on-pdf-invoice">
                  Facture : #<b><%= @invoice.generate_reference %></b>
                  <br>
                  Créée le : <b><%= @invoice.get_creation_date %></b>
                  <br>
                  A payer avant le : <b><%= @invoice.get_due_date %></b>
  <!--                     <br>
                  Statut : <span class="badge badge-primary"><%= @invoice.status %></span> -->
                </td>
              </tr>
            </table>
          </td>
        </tr>

        <tr>
          <td colspan="4">
            <table>
              <tr class="user-and-client-addresses">
                <td class="freelance-address-on-pdf-invoice">
                  <b><%= current_user.first_name + " " + current_user.last_name %></b><br>
                  <b><%= current_user.siret %></b><br>
                  <%= current_user.address %><br>
                  <i class="far fa-envelope"></i> <%= current_user.email %><br>
  <!--                    <i class="fas fa-phone"></i> <%= current_user.phone_number %> -->
                </td>

                <td class="client-address-on-pdf-invoice">
                  <b><%= @invoice.client.first_name + " " + @invoice.client.last_name %></b><br>
                  <%= @invoice.client.company_name %><br>
                  <%= @invoice.client.company_address %><br>
                  <i class="far fa-envelope"></i> <%= @invoice.client.email %><br>
  <!--                     <i class="fas fa-phone"></i> <%= @invoice.client.company_address %> -->
                </td>
              </tr>
            </table>
          </td>
        </tr>

        <tr class="heading">
          <td colspan="6 titre">Titre</td>
          <!-- <td class="right"><%= @invoice.title %></td> -->
        </tr>

        <tr class="details">
          <td><%= @invoice.title %></td>
        </tr>

        <tr class="heading">
          <td>Livrables</td>
          <td class="right">TJH</td>
          <td class="right">Qté</td>
          <td>Total HT</td>
        </tr>


        <% @invoice.missions_invoices.each do |missions_invoice| %>
          <tr class="item">
                <td>
                  <%= missions_invoice.mission.name %><br>
                  <small><%= missions_invoice.mission.description %></small>
                </td>

                <td class="right">
                  <%= missions_invoice.price_rate %> €
                </td>

                <td class="right">
                  <%= missions_invoice.man_day_quantity %>
                </td>

                <td>
                  <%= missions_invoice.man_day_quantity * missions_invoice.price_rate %> €
                </td>
          </tr>
        <% end %>

        <tr>
          <td colspan="4"></td>
        </tr>

        <tr>
          <td colspan="2"></td>
          <td><b>Sous-total HT</b></td>
          <td><%= @invoice.total_amount_ht %> €</td>
        </tr>

        <tr>
          <td colspan="2"></td>
          <td><b>Remise</b></td>
          <td>- 0.00%</td>
        </tr>

        <tr>
          <td colspan="2"></td>
          <td><b>TVA (20.0%)</b></td>
          <td><%= @invoice.total_amount_ht * 0.20 %></td>
        </tr>

        <tr class="heading">
          <td colspan="2"></td>
          <td><b>TOTAL TTC:</b></td>
          <td>
             <b><%= @invoice.total_amount_ttc %> €</b>
          </td>
        </tr>
      </table>
    </div>

  </div>
</body>