config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'


  resources :simulations
  get "/discover", to: "pages#discover", as: "landing_page"

  get 'invoice_paid/:id', to: 'invoices#invoice_paid', as: 'invoice_paid'

  resources :invoices do
    member do
      post :send_to_client
    end

    resources :missions_invoices
  end

  resources :clients, only: [:show, :new, :create, :edit, :update]
  resources :missions, only: [:new, :create]
  resources :notifications, only: [:show, :index, :new, :create]

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount ActionCable.server => "/cable"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_login.html.erb
  <div class="login">
    <ul>
      <% if user_signed_in? %>
        <li class="nav-item-notif dropdown">
          <%= link_to "#", class: "notif-button" do %>
            <i class="fas fa-bell faa-ring"></i>
            <p class="mr-4">Notifications</p>
          <% end %>
          <%= image_tag "user_pic.jpg", class: "avatar-large dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profil", "#", class: "dropdown-item" %>
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item-notif">
          <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>

app/views/shared/_notification_bar.html.erb
<div class="notification-bar">

  <% current_user.notifications.each do |notif| %>
    <%= render 'notifications/show.html.erb', notif: notif %>
  <% end %>

</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar">

  <%= link_to root_path do %>
    <%= image_tag('logo-mae.png', class: 'logo')  %>
  <% end %>

    <div class="navigation-icons">

    <%= link_to root_path do %>
      <div class="icon-and-title">
        <i class="far fa-chart-bar"></i>
        <p>Tableau de bord</p>
      </div>
    <% end %>

    <%= link_to invoices_path do %>
      <div class="icon-and-title">
        <i class="far fa-file-alt icons"></i>
        <p>Factures</p>
      </div>
    <% end %>

    <%= link_to new_simulation_path do %>
      <div class="icon-and-title">
        <i class="fas fa-euro-sign icons"></i>
        <p>Taux de cotisations</p>
      </div>
    <% end %>

  </div>
</div>