config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'


  resources :simulations
  get "/discover", to: "pages#discover", as: "landing_page"

  get 'invoice_paid/:id', to: 'invoices#invoice_paid', as: 'invoice_paid'

  resources :invoices do
    member do
      post :send_to_client
    end

    resources :missions_invoices
  end

  resources :clients, only: [:show, :new, :create, :edit, :update]
  resources :missions, only: [:new, :create]
  resources :notifications, only: [:show, :index, :new, :create]

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount ActionCable.server => "/cable"
end

app/views/pages/discover.html.erb
<!DOCTYPE html>

<html>
<head>
  <meta charset="UTF-8">
  <title>My landing page</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
  <link rel="stylesheet" href="css/style.css">
</head>
<body>

<div class="whole-landing-container">
  <!-- code a Hero / Banner section -->
  <div class="banner">


    <div class="landing-container">

     <!--  <h6>MAE</h6> -->
     <h1><span id="banner-typed-text"></span></h1>
      <%= link_to "Mon espace", root_path, class: "button button-position" %>
    </div>
  </div>

  <!-- code a "How it works" section -->
<!--   <div class="card-container">
    <h2 class="text-center"></h2>
    <div class="cards m-5">

      <div class="card">
        <img src="" alt="">
        <h4>Apply</h4>
        <p>Lorem ipsum dolor sit amet.</p>
      </div>

      <div class="card">
        <img src="" alt="">
        <h4>Learn to code</h4>
        <p>Lorem ipsum dolor sit amet.</p>
      </div>

      <div class="card">
        <img src="" alt="">
        <h4>Build products</h4>
        <p>Lorem ipsum dolor sit amet.</p>
      </div>

    </div>
  </div> -->

  <!-- code a footer -->
  <div class="footer">
    <div class="links">
      <a href="#"><i class="fab fa-fw fa-facebook-f"></i></a>
      <a href="#"><i class="fab fa-fw fa-github"></i></a>
      <a href="#"><i class="fab fa-fw fa-twitter"></i></a>
      <a href="#"><i class="fab fa-fw fa-instagram"></i></a>
      <p>This website was coded with <i class="fas fa-heart"></i> at Le Wagon.</p>

    </div>
  </div>

</div>

</body>
</html>

app/views/pages/home.html.erb
<div class="homepage-container">

  <div class="top-div-homepage">
    <div class="welcome-card">
      <h2>Bonjour <%= current_user.first_name %> !</h2>
      <p>Que souhaitez-vous faire aujourd'hui ?</p>
      <div class="two-actions-from-homepage-card">
        <%= link_to "Créer une nouvelle facture", new_invoice_path, class: "button" %>
        <%= link_to "Gérer mes factures", invoices_path, class: "second-button-on-the-right button-white-background-and-yellow-text" %>
      </div>
      <img class="illustration" src="<%= image_path('undraw_balloons_vxx5.svg') %>"/>
    </div>

    <div class="cotisations-time d-flex flex-column">
      <h2> Mes cotisations </h2>

      <div class="reglement-cotisations d-flex">
        <div class="sum-to-pay" data-quarter="<%= @income_per_current_quarter_to_pay.to_json %>"></div>
      </div>

        <div class="payment-date"> </div>
        <div class="call-simul"> </div>

      <div class="small d-flex justify-content-between" id="current-user-rate" data-rate="<%= current_user.tax_rate.to_json %>"></div>
    </div>

  </div>

  <div class="second-div-homepage">
    <div class="turnover-chart-card" style="width: 480px">
      <div class="turnover-chart chart">
        <canvas id="chart-bars" class="chart-canvas chartjs-render-monitor" data-months="<%= @income_months.to_json %>" data-values="<%= @income_values.to_json %>"></canvas>
      </div>
    </div>

    <div class="mes-factures-chart-card" style="width: 500px">
      <canvas id="myChart" data-submitted="<%=current_user.get_total_submitted.to_json %>" data-delayed="<%=current_user.get_total_delayed.to_json %>" data-paid="<%= current_user.get_total_paid.to_json %>" data-paid-quarter="<%= @income_per_current_quarter.to_json %>"></canvas>
    </div>
  </div>


  <div class="invoices-cards-div">

    <div class="invoices-status">
      <div class="invoices-sent">
        <ul class="list-group list-group-flush" data-toggle="checklist">

          <div class="column-title d-flex justify-content-between align-items-center">
            <div>
              <h3>Factures envoyées</h3>
              <div class="total_submitted">
                <%= number_with_delimiter(current_user.get_total_submitted.round, delimiter: " ") %> €
              </div>
            </div>
            <div class="invoices-counted-with-circle-blue">
              <%= @invoices.sent.count %>
            </div>
          </div>

          <% @invoices.each do |invoice| %>
            <% if invoice.sent? %>
              <li class="checklist-entry list-group-item flex-column align-items-start">
                <div class="checklist-item checklist-item-success">
                  <div class="checklist-info">
                    <i class="status-colored-circle sent fas fa-circle"></i>
                    <div class="homepage-invoice-infos">
                      <h5 class="checklist-title mb-0"><%= invoice.title %> - <%= invoice.client.company_name %></h5>
                      <small><%=  number_with_delimiter(invoice.total_amount_ttc.round, delimiter: " ") %> €</small>
                      <%= link_to '', invoice_paid_path(invoice), class: "hidden-link"  %>
                    </div>
                  </div>

                  <div class="actions-on-invoices-buttons">
                    <div class="mark-as-paid-button">
                      <i class="mark-as-paid-icon fas fa-check" title="Marquer comme payée"></i>
                    </div>
                  </div>
                </div>
              </li>
            <% end %>
          <% end %>

        </ul>
      </div>
    </div>


    <div class="invoices-status">
      <div class="invoices-delayed">
        <ul class="list-group list-group-flush" data-toggle="checklist">

          <div class="column-title d-flex justify-content-between align-items-center">
            <div>
              <h3>Factures en retard</h3>
              <div class="total_delayed">
                <%= number_with_delimiter(current_user.get_total_delayed.round, delimiter: " ") %> €
              </div>
            </div>
            <div class="invoices-counted-with-circle-pink">
              <%= @invoices.delayed.count %>
            </div>
          </div>

          <% @invoices.each do |invoice| %>
            <% if invoice.delayed? %>
              <li class="checklist-entry list-group-item flex-column align-items-start">
                <div class="checklist-item checklist-item-success">
                  <div class="checklist-info">
                    <i class="status-colored-circle delayed fas fa-circle"></i>
                    <div class="homepage-invoice-infos">
                      <h5 class="checklist-title mb-0"><%= invoice.title %> - <%= invoice.client.company_name %></h5>
                      <small>
                        <%=  number_with_delimiter(invoice.total_amount_ttc.round, delimiter: " ") %> €
                      </small>
                      <%= link_to '', invoice_paid_path(invoice), class: 'hidden-link' %>
                    </div>
                  </div>

                  <div class="actions-on-invoices-buttons">
                    <div class="mark-as-paid-button">
                      <i class="mark-as-paid-icon fas fa-check" title="Marquer comme payée"></i>
                    </div>
                    <div class="late-client-button">
                      <i class="late-client-icon fas fa-user-clock" title="Relancer"></i>
                    </div>
                  </div>
                </div>
              </li>
            <% end %>
          <% end %>

        </ul>
      </div>
    </div>

  <div class="invoices-status">
    <div class="invoices-paid">
      <ul class="list-group list-group-flush" data-toggle="checklist">

        <div class="column-title d-flex justify-content-between align-items-center">
          <div>
            <h3>Factures payées</h3>
            <div class="total_paid">
              <%= number_with_delimiter(current_user.get_total_paid.round, delimiter: " ") %> €
            </div>
          </div>
          <div class="invoices-counted-with-circle-green">
            <%= @invoices.paid.count %>
          </div>
        </div>

        <% @invoices.each do |invoice| %>
          <% if invoice.paid? %>
            <li class="checklist-entry list-group-item flex-column align-items-start">
              <div class="checklist-item checklist-item-success">
                <div class="checklist-info">
                  <i class="status-colored-circle paid fas fa-circle"></i>
                  <div>
                    <h5 class="checklist-title mb-0"><%= invoice.title %> - <%= invoice.client.company_name %></h5>
                    <small><%=  number_with_delimiter(invoice.total_amount_ttc.round, delimiter: " ") %> €</small>
                  </div>
                </div>
              </li>
            <% end %>
          <% end %>

        </ul>
      </div>
    </div>


  </div>
</div>